channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cffi=1.12.3
  - cryptography=2.7
  - entrypoints=0.3
  - flake8=3.7.7
  - idna=2.8
  - importlib_metadata=0.19
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - mccabe=0.6.1
  - more-itertools=7.2.0
  - ncurses=6.1
  - openssl=1.1.1d
  - packaging=19.1
  - pip=19.2.2
  - pluggy=0.12.0
  - py=1.8.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pysocks=1.7.0
  - pytest=5.0.1
  - python=3.7.4
  - readline=7.0
  - selenium=3.141.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - urllib3=1.24.2
  - wcwidth=0.1.7
  - wheel=0.33.4
  - xz=5.2.4
  - zipp=0.5.2
  - zlib=1.2.11
  - pip:
    - appium-python-client==0.47
